<?php

$color_schemes['default'] = array(
    'label' => __('Default', 'ctheme-name'),
    'colors' => array(
        'theme_name_colors[menu_link_bg_color]' => '#fede00',
        'theme_name_colors[heading2_color]' => '#ffffff',
        'theme_name_colors[icon-color]' => '#fede00',
        'theme_name_colors[link_color]' => '#1c1c1c',
        'theme_name_colors[link_hover_color]' => '#000000',
        'theme_name_colors[heading_active_color]' => '#fede00',
        'theme_name_colors[text_white_color]' => '#ffffff',
        'theme_name_colors[white_icon-color]' => '#ffffff',
        'theme_name_colors[menu_link_color]' => '#000000',
        'theme_name_colors[slider_text2_color]' => '#fede00',
        'theme_name_colors[slider_navi_color]' => '#ffffff',
        'theme_name_colors[button_bg_color]' => '#fede00',
        'theme_name_colors[button_text_color]' => '#000000',
        'theme_name_colors[button_bg_hover_color]' => '#000000',
        'theme_name_colors[button2_bg_color]' => '#2c2c2c',
        'theme_name_colors[theme_comon_bg_color]' => '#fede00',
        'theme_name_colors[theme_comon_text_color]' => '#fede00',
        'theme_name_colors[theme_apoint_bg_color]' => '#fede00',
        'theme_name_colors[theme_apoint_angle_color]' => '#fede00',
        'theme_name_colors[preloader_color]' => '#fede00',
        'theme_name_colors[body_color]' => '#292929',
        'theme_name_colors[comon_border_color]' => '#fede00',
        'theme_name_colors[pricing_bg_color]' => '#fede00',
        'theme_name_colors[pricing_border_color]' => '#fede00',
        'theme_name_colors[button_border_color]' => '#fede00',
        'theme_name_colors[button_hv_color]' => '#fede00',
        'theme_name_colors[slider_navi_hover_color]' => '#fede00',
        'theme_name_colors[heading_color]' => '#292929',
        'theme_name_colors[slider_dot_hover_color]' => '#fede00',
        'theme_name_colors[shop_sale_text_color]' => '#000000',
        'theme_name_colors[shop_sale_color]' => '#fede00',
        'theme_name_colors[auto_search_icon_color]' => '#d9d9d9',
        'theme_name_colors[auto_search_button_color]' => '#444444',
        'theme_name_colors[auto_search_button_text_color]' => '#ffffff',
        'theme_name_colors[shop_pagination_bg_color]' => '#fede00',
        'theme_name_colors[shop_pagination_text_color]' => '#000000',
        'theme_name_colors[shop_pagination_border_color]' => '#fede00',
        'theme_name_colors[cart_icon_color]' => '#fede00',
        'theme_name_colors[shop_filter_color]' => '#fede00',
        'theme_name_colors[shop_rateing_color]' => '#fede00',
        'theme_name_colors[shop_button_bg_color]' => '#fede00',
        'theme_name_colors[coupon_title_color]' => '#ffffff',
        'theme_name_colors[coupon_subtitle_color]' => '#fede00',
        'theme_name_colors[coupon_button_color]' => '#fede00',
        'theme_name_colors[coupon_button_text_color]' => '#000000',
        'theme_name_colors[coupon_button_hover_color]' => '#ffffff',
        'theme_name_colors[coupon_button_text_hover_color]' => '#000000',
        'theme_name_colors[services_icon_shadow]' => '#fede00',
        'theme_name_colors[slider_text_color]' => '#ffffff',
        'theme_name_colors[button2_text_color]' => '#ffffff',
        'theme_name_colors[red_text_color]' => '#dd3333',
        'theme_name_colors[coupon_border_color]' => '#fede00',
        'theme_name_colors[blog_celender_color]' => '#24d650',
        'theme_name_colors[button_hover_text_color]' => '#ffffff',
        'theme_name_colors[auto_search_button_hover_color]' => '#fede00',
        'theme_name_colors[auto_search_button_text_hover_color]' => '#fede00'
        
    ),
);

